version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/BASE
hooks:
  BeforeInstall:
    - location: AWS_install_scripts/prepareInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: AWS_install_scripts/installApp.sh
      timeout: 600
      runas: root
---
